### ISSUE TITLE
feat: plugin for generating responsive images

### ISSUE THREAD

**Issue by krmax44** [saberland/saber#147]
[<img alt="Issuehunt badges" src="https://issuehunt.io/r/egoist/saber/issues/147/badge.svg" />](https://issuehunt.io/r/egoist/saber/issues/147)

## Feature request

Plugin that generates responsive images and applies some magic image optimization with optional lazy-loading. Similar to what Gatsby does with `gatsby-image`.

#### What problem does this feature solve?

Slow load times when images are unnecessarily large or not in viewport (with lazy-loading enabled) and developer pain when they have to resize their images manually.

#### What does the proposed API look like?

```yml
# saber-config.yml

plugins:
  - resolve: saber-plugin-image
    sizes:
      large: 1000
      medium: 600
      small: 400
    lazyload: true
    blur: true
```

#### How should this be implemented in your opinion?

Using something like [responsive-loader](https://github.com/herrstucki/responsive-loader) and [vue-lazyload](https://github.com/hilongjw/vue-lazyload)

#### Are you willing to work on this yourself?

Yes.

> There is a $60.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/egoist/saber/issues/147).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/saber/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.
