### ISSUE TITLE
Global components

### ISSUE THREAD

**Issue by krmax44** [saberland/saber#515]
## Feature request

Allow the user to register components globally, without digging in configs.

#### What problem does this feature solve?

When using components like `<warning-message>Heads up!</warning-message>` oftenly throughout Markdown, it becomes repetetive to add a script block that imports and registers the component.

#### What does the proposed API look like?

```
📦 current working directory
 ┣ 📂 theme
     ┣ 📂 components
         ┣ 📂 global
             ┣ 📄 myGlobalThemeComponent.vue
 ┣ 📂 pages
 ┣ 📂 components
     ┣ 📄 myGlobalComponent.vue
```

Maybe also configurable:

```yml
build:
  globalComponents: false # disable it alltogether
  globalComponents: # all Vue files in these folders will be loaded as global components
    - components/
    - theme/foo-bar/
```

#### How should this be implemented in your opinion?

Probably as core functionality, possibly as a plugin if desired.

#### Are you willing to work on this yourself?

Yes.
